#services:
#  paras-server:
#    command:
#      - conda
#      - run
#      - --no-capture-output
#      - -n
#      - web
#      - gunicorn
#      - api:app
#      - --bind
#      - 0.0.0.0:4009
#      - --reload
#      - --workers
#      - "1"
#      - --threads
#      - "4"
#      - --timeout
#      - "120"
#    volumes:
#      - ./src/server:/app
#      - ./models:/app/models:ro
#    restart: "no"
#    environment:
#      - LOG_LEVEL=DEBUG
#      - FLASK_ENV=development
#
#  paras-client-dev:
#    image: node:20-alpine
#    working_dir: /app
#    ports:
#      - "3000:3000"
#    volumes:
#      - ./src/client:/app          # live mount your client code
#      - /app/node_modules          # keeps node_modules inside container, not on Windows
#    environment:
#      - CHOKIDAR_USEPOLLING=true   # fixes file watching on Windows
#      - WATCHPACK_POLLING=true     # same fix for webpack
#    command: sh -c "npm install && npm start"
#    networks: [paras-network]
#    depends_on:
#      - paras-server